### Get All the messages
GET http://localhost:3000


### Add a new Message via JSON
POST http://localhost:3000/new
Content-Type: application/json

{
    "text": "Esto es un mensaje de prueba",
    "user": "AnderGi"
}


### Add a new Message via post form
POST http://localhost:3000/new
Content-Type: application/x-www-form-urlencoded

user=Ander
&text=Hola que tal